name: Wheels

on: [push]

jobs:
  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        java-package: jre
        architecture: x64

    - name: Set up env (Windows)
      if: matrix.os == 'windows-latest'
      run: .github/workflows/bin/setup_env_win.bat

    - name: Set up env (macOS)
      if: matrix.os == 'macos-latest'
      run: .github/workflows/bin/setup_env_macos.sh

    - uses: pypa/cibuildwheel@v2.1.1
      env:
        #CIBW_BEFORE_ALL:
        CIBW_BUILD: "cp36-*"
        CIBW_BEFORE_ALL_LINUX: >
          {package}/.github/workflows/bin/setup_env_linux.sh
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_SKIP: "pp* *win32 *i686"
        MACOSX_DEPLOYMENT_TARGET: "10.15"
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_TEST_COMMAND: >
          surelog

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl

  # publish:
  #   needs: [build_wheels]
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'release' && github.event.action == 'published' && !contains(github.event.release.body, 'NOPUBLISH')

  #   steps:
  #   - uses: actions/download-artifact@v2
  #     with:
  #       name: artifact
  #       path: dist

  #   - uses: pypa/gh-action-pypi-publish@v1.4.2
  #     with:
  #       user: __token__
  #       password: ${{ secrets.PYPI_DEPLOY }}
